### ISSUE TITLE
Failed to interpret file 'datasets/UNSW-NB15/edge_feat_scaled.npy' as a pickle

### ISSUE THREAD

**Issue by ylic204** [George730/E-ResGAT#4]
Dear authors,

Thank you for uploading this code. I am a beginner in  anomaly detection and this has been very helpful in my research. 
I have read the original article corresponding to that code. When I try to run the program, "fit_model.py", the program prompts an error, 'datasets/UNSW-NB15edge_feat_scaled.npy' could not be found, so I changed the path and the program reports the following error：

path: datasets/UNSW-NB15/
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/numpy/lib/npyio.py", line 460, in load
    return pickle.load(fid, **pickle_kwargs)
_pickle.UnpicklingError: invalid load key, 'v'.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "fit_model.py", line 180, in <module>
    fit(args)
  File "fit_model.py", line 40, in fit
    edge_feat, label, adj, adj_lists, config = load_gat(path, device, binary)
  File "/content/gdrive/MyDrive/Colab Notebooks/E-ResGAT-master/loader.py", line 58, in load_gat
    edge_feat = np.load(path + "edge_feat_scaled.npy", allow_pickle=True)  
  File "/usr/local/lib/python3.7/dist-packages/numpy/lib/npyio.py", line 463, in load
    "Failed to interpret file %s as a pickle" % repr(file))
OSError: Failed to interpret file 'datasets/UNSW-NB15/edge_feat_scaled.npy' as a pickle

![QQ图片20220522100645](https://user-images.githubusercontent.com/90877396/169675193-3e713a71-b30b-4f65-8462-35c28c58faa1.png)

And all the dataset "edge_feat_scaled.npy" is similar. So I tried to download it using git lfs, but it's still the same after downloading. How can I solve this problem? 

Thanks for any help.
Regards,
LiY

**Comment by ylic204** [comment]
Also, the authors get `edge_feat_scaled.npy` via `UNSW_prepare.ipynb`.
`unsw = pd.read_csv("UNSW-NB15_1.csv`, header=None)".
But the author did not provide the file. So I downloaded the NF-UNSW-NB15 dataset from the web, but the result after loading is different from the original UNSW_prepare.ipynb after running, e.g. `len(unsw) = 700001`, while the downloaded NF-UNSW-NB15 has `len(unsw) = 1623119`. Therefore, I would like to know if the author can provide that dataset?

**Comment by George730** [comment]
The NF-UNSW-NB15 is a different dataset in NetFlow data type. The UNSW-NB15 dataset is downloaded from [this website](https://research.unsw.edu.au/projects/unsw-nb15-dataset). Check that there is a partition into four dataset csv. Here just uses the first csv file named UNSW-NB15_1.csv. For more information on how the data is preprocessed, you can check [this paper](https://arxiv.org/abs/2111.13597).

**Comment by Avancez** [comment]
> Dear authors,
> 
> Thank you for uploading this code. I am a beginner in anomaly detection and this has been very helpful in my research. I have read the original article corresponding to that code. When I try to run the program, "fit_model.py", the program prompts an error, 'datasets/UNSW-NB15edge_feat_scaled.npy' could not be found, so I changed the path and the program reports the following error：
> 
> path: datasets/UNSW-NB15/ Traceback (most recent call last): File "/usr/local/lib/python3.7/dist-packages/numpy/lib/npyio.py", line 460, in load return pickle.load(fid, **pickle_kwargs) _pickle.UnpicklingError: invalid load key, 'v'.
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last): File "fit_model.py", line 180, in fit(args) File "fit_model.py", line 40, in fit edge_feat, label, adj, adj_lists, config = load_gat(path, device, binary) File "/content/gdrive/MyDrive/Colab Notebooks/E-ResGAT-master/loader.py", line 58, in load_gat edge_feat = np.load(path + "edge_feat_scaled.npy", allow_pickle=True) File "/usr/local/lib/python3.7/dist-packages/numpy/lib/npyio.py", line 463, in load "Failed to interpret file %s as a pickle" % repr(file)) OSError: Failed to interpret file 'datasets/UNSW-NB15/edge_feat_scaled.npy' as a pickle
> 
> ![QQ图片20220522100645](https://user-images.githubusercontent.com/90877396/169675193-3e713a71-b30b-4f65-8462-35c28c58faa1.png)
> 
> And all the dataset "edge_feat_scaled.npy" is similar. So I tried to download it using git lfs, but it's still the same after downloading. How can I solve this problem?
> 
> Thanks for any help. Regards, LiY



> Dear authors,
> 
> Thank you for uploading this code. I am a beginner in anomaly detection and this has been very helpful in my research. I have read the original article corresponding to that code. When I try to run the program, "fit_model.py", the program prompts an error, 'datasets/UNSW-NB15edge_feat_scaled.npy' could not be found, so I changed the path and the program reports the following error：
> 
> path: datasets/UNSW-NB15/ Traceback (most recent call last): File "/usr/local/lib/python3.7/dist-packages/numpy/lib/npyio.py", line 460, in load return pickle.load(fid, **pickle_kwargs) _pickle.UnpicklingError: invalid load key, 'v'.
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last): File "fit_model.py", line 180, in fit(args) File "fit_model.py", line 40, in fit edge_feat, label, adj, adj_lists, config = load_gat(path, device, binary) File "/content/gdrive/MyDrive/Colab Notebooks/E-ResGAT-master/loader.py", line 58, in load_gat edge_feat = np.load(path + "edge_feat_scaled.npy", allow_pickle=True) File "/usr/local/lib/python3.7/dist-packages/numpy/lib/npyio.py", line 463, in load "Failed to interpret file %s as a pickle" % repr(file)) OSError: Failed to interpret file 'datasets/UNSW-NB15/edge_feat_scaled.npy' as a pickle
> 
> ![QQ图片20220522100645](https://user-images.githubusercontent.com/90877396/169675193-3e713a71-b30b-4f65-8462-35c28c58faa1.png)
> 
> And all the dataset "edge_feat_scaled.npy" is similar. So I tried to download it using git lfs, but it's still the same after downloading. How can I solve this problem?
> 
> Thanks for any help. Regards, LiY
你成功了吗？

**Comment by wlmnzf** [comment]
@George730 @ylic204 @Avancez In the ```datasets``` directory, each dataset has a ```*** _prepare.ipynb```, according to the needed file name inside, for example ```XXX.csv```, search this file name in Google directly, download it, execute this ipynb file, you can get the  "edge_feat_scaled.npy" .
