### ISSUE TITLE
无法绘制正确的散点图，请求发布完整的代码

### ISSUE THREAD

**Issue by jkup64** [George730/E-ResGAT#7]
您好，我对您的研究很感兴趣，但我在复现的过程中遇到了一些问题：
`fit_model.py`中的命令行参数设置存在语法问题：
```python
p.add_argument('--binary',
                   help='Perform binary or muticlass task',
                   #action='store_true',
                   type=bool,
                   default=True)
```
对于bool类型参数设置，无法怎么设置binary都是True，这是很基础的语法问题。
此外，我修改后模型的多分类任务上准确率能够达到98.45%，各个类别得分正常，但是绘制的散点图没有`visualization.ipynb`中的效果，我恳请您能提供一份完整的最终代码，我的邮箱为`919863493@qq.com`，谢谢。
![image](https://user-images.githubusercontent.com/65334542/233655283-75bf69f6-ec4d-408c-ba8b-10ed4f48a650.png)

**Comment by Fabiabn** [comment]
你好 visualization.ipynb中的UNSW-NB15的test与 emb.npy文件从何来

**Comment by George730** [comment]
Thanks for pointing out the issue in argparser.

For visualization, I guess there are few you can try:

- you need to use more data points (I used 5000 points). 
- use t-SNE instead of PCA
- use the features from the last second layer, which is right before fully connection, for visualization

**Comment by lhr42** [comment]
> 你好 visualization.ipynb中的UNSW-NB15的test与 emb.npy文件从何来

您好，请问您解决了吗？

**Comment by jkup64** [comment]
我当时代码写的有问题，你要做这个方向吗，你是本科还是研究生吗，感觉这个方向有点坑喔



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年5月3日(周五) 晚上9:45
收件人: ***@***.***&gt;;
抄送: "Kaian ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [George730/E-ResGAT] 无法绘制正确的散点图，请求发布完整的代码 (Issue #7)




  
你好 visualization.ipynb中的UNSW-NB15的test与 emb.npy文件从何来
  
您好，请问您解决了吗？
